/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAusenciasRouteImport } from './routes/_authenticated/ausencias'
import { Route as AuthenticatedEmpleadosRouteImport } from './routes/_authenticated/empleados'
import { Route as AuthenticatedFichajesRouteImport } from './routes/_authenticated/fichajes'
import { Route as AuthenticatedFicharRouteImport } from './routes/_authenticated/fichar'
import { Route as AuthenticatedNominasRouteImport } from './routes/_authenticated/nominas'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAusenciasRoute = AuthenticatedAusenciasRouteImport.update({
  id: '/_authenticated/ausencias',
  path: '/ausencias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpleadosRoute = AuthenticatedEmpleadosRouteImport.update({
  id: '/_authenticated/empleados',
  path: '/empleados',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFichajesRoute = AuthenticatedFichajesRouteImport.update({
  id: '/_authenticated/fichajes',
  path: '/fichajes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFicharRoute = AuthenticatedFicharRouteImport.update({
  id: '/_authenticated/fichar',
  path: '/fichar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNominasRoute = AuthenticatedNominasRouteImport.update({
  id: '/_authenticated/nominas',
  path: '/nominas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/_authenticated/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/fichajes': typeof AuthenticatedFichajesRoute
  '/fichar': typeof AuthenticatedFicharRoute
  '/nominas': typeof AuthenticatedNominasRoute
  '/panel': typeof AuthenticatedPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ausencias': typeof AuthenticatedAusenciasRoute
  '/empleados': typeof AuthenticatedEmpleadosRoute
  '/fichajes': typeof AuthenticatedFichajesRoute
  '/fichar': typeof AuthenticatedFicharRoute
  '/nominas': typeof AuthenticatedNominasRoute
  '/panel': typeof AuthenticatedPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/_authenticated/ausencias': typeof AuthenticatedAusenciasRoute
  '/_authenticated/empleados': typeof AuthenticatedEmpleadosRoute
  '/_authenticated/fichajes': typeof AuthenticatedFichajesRoute
  '/_authenticated/fichar': typeof AuthenticatedFicharRoute
  '/_authenticated/nominas': typeof AuthenticatedNominasRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ausencias'
    | '/empleados'
    | '/fichajes'
    | '/fichar'
    | '/nominas'
    | '/panel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ausencias'
    | '/empleados'
    | '/fichajes'
    | '/fichar'
    | '/nominas'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/_authenticated/ausencias'
    | '/_authenticated/empleados'
    | '/_authenticated/fichajes'
    | '/_authenticated/fichar'
    | '/_authenticated/nominas'
    | '/_authenticated/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuthenticatedAusenciasRoute: typeof AuthenticatedAusenciasRoute
  AuthenticatedEmpleadosRoute: typeof AuthenticatedEmpleadosRoute
  AuthenticatedFichajesRoute: typeof AuthenticatedFichajesRoute
  AuthenticatedFicharRoute: typeof AuthenticatedFicharRoute
  AuthenticatedNominasRoute: typeof AuthenticatedNominasRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ausencias': {
      id: '/_authenticated/ausencias'
      path: '/ausencias'
      fullPath: '/ausencias'
      preLoaderRoute: typeof AuthenticatedAusenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empleados': {
      id: '/_authenticated/empleados'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof AuthenticatedEmpleadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fichajes': {
      id: '/_authenticated/fichajes'
      path: '/fichajes'
      fullPath: '/fichajes'
      preLoaderRoute: typeof AuthenticatedFichajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fichar': {
      id: '/_authenticated/fichar'
      path: '/fichar'
      fullPath: '/fichar'
      preLoaderRoute: typeof AuthenticatedFicharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/nominas': {
      id: '/_authenticated/nominas'
      path: '/nominas'
      fullPath: '/nominas'
      preLoaderRoute: typeof AuthenticatedNominasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuthenticatedAusenciasRoute: AuthenticatedAusenciasRoute,
  AuthenticatedEmpleadosRoute: AuthenticatedEmpleadosRoute,
  AuthenticatedFichajesRoute: AuthenticatedFichajesRoute,
  AuthenticatedFicharRoute: AuthenticatedFicharRoute,
  AuthenticatedNominasRoute: AuthenticatedNominasRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
